### ISSUE TITLE
add examples

### ISSUE THREAD

**Issue by bigerl** [dice-group/dice-hash#14]
We need examples/elaboration for at least:
- [x] hashing a string and an int
- [x] using it in `std::unordered_map` and `std::unordered_set`
- [x] defining `dice_hash` for a custom type
- [x] `is_unordered_container_v` and `is_ordered_container_v`

**Comment by bigerl** [comment]
@LukasKerk what do you think: should we add example .cpp files in a subfolder examples or should we provide the description how to use it in the readme?

**Comment by LukasKerk** [comment]
#17 does all of it. However it still needs some work.
