### ISSUE TITLE
make combine functions available

### ISSUE THREAD

**Issue by bigerl** [dice-group/dice-hash#15]
- [x] `dice_hash_invertible_combine` should be available with an arbitrary number of arguments in namespace `Dice::hash`. Arguments should be size_t.  
- [x] additionally, `dice_hash_combine` should also be with an arbitrary number of arguments in namespace `Dice::hash`. Arguments should be size_t. 
- [x] add examples how to use above functions
- [x] add tests for above functions

**Comment by LukasKerk** [comment]
See #18
