### ISSUE TITLE
setup github actions for the project

### ISSUE THREAD

**Issue by bigerl** [dice-group/dice-hash#5]
- [x] automatic deployment of tags as conan packages
- [x] build with gcc + clang (on pushs and on merge requests)
- [x] run tests (on pushs and on merge requests)
- [x] generate single-header-file and add it as "attached binary" to releases. tools that can generate single-header-files: https://stackoverflow.com/questions/50887018/cmake-generate-single-header-file

**Comment by LukasKerk** [comment]
#3 does a few of these things allready. It will be extended to fulfill all the criteria.
